#install.packages("randomForest")
#install.packages(c("ModelMetrics", "plyr", "pROC", "reshape2"))
install.packages(c("RcppTOML", "reticulate", "tfruns", "tfautograph"))
install.packages("keras")
#install.packages("caret")
